language: node_js
node_js: lts/*
cache: npm

install: npm ci
script: npm test
before_deploy: rm -rf examples/ docs/ **/__tests__ **/__helpers__ **/__fixtures__ contributing.md
deploy:
  provider: npm
  email: leonardo.sarmentocastro@gmail.com
  api_key: "SECRETS_NPM_TOKEN"
  on:
    tags: true
